### PR TITLE
Add the dependencies to kernel

### PR DESCRIPTION
**Pull request by harikt**

### CODE REVIEW

**Comment by harikt** [comment]
@pmjones will you merge the composer.json to master, so the packagist knows the dependencies ?

**Comment by pmjones** [comment]
Strangely, this is something I want to avoid. There was a point in the v1 framework where I wanted to use a develop version of a library, but could not, because the dependency was at the lower (Aura.Framework) level, and not at the upper (system) level where I could edit it directly.  The Kernel and Project are intended to go together anyway, so I don't think keeping the dependency at the upper (Project) level will be a real problem.

**Comment by harikt** [comment]
may be then we should add in suggest alteast.

**Comment by harikt** [comment]
@pmjones one question to undertand for clarity , I feel we only need Web_Kernel , why did you added a Web_Project also ?

Can't the files be in the kernel level itself ?

**Comment by pmjones** [comment]
They _could_ be, but then you can't update the kernel files independently of the project.  This is actually the same setup we have now under v1, just with different names. The "kernel" is the equivalent of "Aura.Framework" and the "project" is the equivalent of "system".

**Pull request closed without merging**
