### PR TITLE
Simpler tests

### PR DESCRIPTION
**Pull request by mbrevda**
Simplify tests, improve phpunit.sh, move composer related housekeeping to .travis.yml, speed up travis build times by caching depends between builds, add `composer test` command 

Once https://github.com/auraphp/Aura.Web/pull/46 is merged, the bootstrap file can be removed as well

### CODE REVIEW

**Comment by harikt** [comment]
Another one https://github.com/auraphp/Aura.Router/pull/72 . I do wish not to copy and remove the phpunit.sh .

**Comment by mbrevda** [comment]
@harikt I do not understand

**Comment by harikt** [comment]
nothing @mbrevda . Just mentioning another PR which I love some changes how the unit test works.

**Comment by pmjones** [comment]
I think this is obviated by the recent changes to which @harikt alluded above. Let me know if these recent changes solve the issues you addressed, and if not, we can address them.

**Comment by mbrevda** [comment]
Yeah, were more or less on the same page. I might still recommend:
1. Adding a `composer test` command (to all packages, eventually, not just this)
2. Include composers autoload as the phpunit bootstrap file - cuts out the need for a standalone bootstrap.php

**Pull request closed without merging**
